version: '3'
services:
    music-utils:
        build: .
        image: yumemo/music-utils
        container_name: music-utils
        hostname: music-utils
        tty: true
        volumes:
            - .:/opt/music-utils
