name: Create index page for github pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install required module
      run: pip install jinja2
    - name: Run python script
      run: python scripts/create_index.py > index.html