name: Create index page for github pages
on:
  push:
    branches-ignore:
      - master

jobs:
  pr:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install required module
      run: pip3 install jinja2 BeautifulSoup4 lxml

    - name: Run python script
      run: python3 scripts/create_index.py > index.html

    - name: Create pull request
      uses: peter-evans/create-pull-request@v2.4.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Create PR from ${{ GITHUB_REF::11 }}
        branch: ci/${{ GITHUB_REF::11 }}