name: Create index page for github pages
on:
  push:
    branches-ignore:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set branch var
      id: branch
      run: echo "::set-output name=branch::${GITHUB_REF:11}"

    - name: Install required module
      run: pip3 install jinja2 BeautifulSoup4 lxml

    - name: Run python script
      run: python3 scripts/create_index.py > index.html

    - name: Create pull request to master
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: master
        title: Create PR from ${{ steps.branch.outputs.branch }}
        branch: ci/${{ steps.branch.outputs.branch }}
        delete-branch: true
